language: ruby
dist: trusty
sudo: false
node_js:
- node
before_script:
- npm install ajv-cli
- PATH="./node_modules/.bin/:$PATH"
script:
- bundle exec jekyll build
- ajv test -s schema -d address -d calendar -d card -d geo --valid
- ajv test -s schema -d "_includes/example/*.json" --valid
